### ISSUE TITLE
Not able to send messages to broker outside the network

### ISSUE THREAD

**Issue by rsingh2411** [mesos/kafka#139]
Hi, i am using public private ip, i am able to send and recieve messages from the kafka client  machine present in same network , however i am receiving error 
kafka.common.FailedToSendMessageException: Failed to send messages after 3 tries.
    at kafka.producer.async.DefaultEventHandler.handle(DefaultEventHandler.scala:90)
    at kafka.producer.Producer.send(Producer.scala:77)
    at kafka.javaapi.producer.Producer.send(Producer.scala:33)
    at com.KafkaProducer.run(KafkaProducer.java:35)
    at App.main(App.java:20)
from outside the network while sending messages. Any pointers

**Comment by joestein** [comment]
The broker advertises itself based the host you bind too. You also have the ability to bind to one host and advertise another. https://cwiki.apache.org/confluence/display/KAFKA/FAQ#FAQ-Whycan'tmyconsumers/producersconnecttothebrokers?

You can either make the other network routable to the IP and or DNS that the broker is advertising on, change the bind (via --bind-address) or what you are advertising the broker as via --options

by default the broker binds to the host in request (so either host of slave or ip if you set the ip instead of the host in mesos config)
