### ISSUE TITLE
delete topics from CLI

### ISSUE THREAD

**Issue by eastlondoner** [mesos/kafka#186]
Loving kafka on mesos.

I know that Kafka support for deleting topics has historically been patchy but it is supported now. It would be great to add this to the CLI for topics.

I've created a load of "test" and "foo" topics and I would like to get rid of them but it's very difficult!

**Comment by joestein** [comment]
What version of Kafka are you running?

We didn't originally put in support for delete topic because it was still stabilizing since when we started the scheduler. It is a supported feature with good backing and yes should be something we add in the scheduler api if PR to review great maybe can get to it up coming sprints

**Comment by eastlondoner** [comment]
I'm using a 0.9 version of Kafka so deleting topics is supported - I have been able to do it, it is just a pain -  I'd love to see this implemented in the dcos CLI.

**Comment by joestein** [comment]
We have the feature on our roadmap will see when we plan to get to it, if someone wants to post a PR we can review and commit it if it works and reasons right in the code, etc. Definitely more completely scheduler admin api is important.

**Comment by clehene** [comment]
I'll have a PR submitted. once I test it.

**Comment by vmahedia** [comment]
@clehene Looking forward to your PR, we need this too.

**Comment by clehene** [comment]
@vmahedia please try it out
