### ISSUE TITLE
Add Dockerfile for kafka scheduler

### ISSUE THREAD

**Issue by tnachen** [mesos/kafka#29]
We want a Dockerfile that can build the kafka scheduler and keep the artifacts (jar) to run the scheduler itself.

**Comment by dmitrypekar** [comment]
Hi Timothy.

If I understood you correctly, you propose to use docker for building and running the scheduler itself.
Sorry, but I see no reason of doing so, because the scheduler itself already could be built and run without docker using OS shell only.

Please correct me, if I've missed something or made a mistake in my assumptions.

**Comment by keithchambers** [comment]
We find that Dockers ability to package up software including all the dependencies (like Java) and Docker Hub (the omnipresent artifact repo in the sky) make it dead simple to package and push -> hub -> pull and run on any disto.

**Comment by joestein** [comment]
in progress #33

**Comment by joestein** [comment]
taken care of in #35
