### ISSUE TITLE
Brokers should use disk resources and set log.retention.bytes

### ISSUE THREAD

**Issue by guenter** [mesos/kafka#49]
Currently, a broker can fill up the disk on slaves entirely. Brokers should set `log.retention.bytes` and use disk resources to prevent this.

**Comment by dmitrypekar** [comment]
Please use --options for that. Unfortunately, I see no reliable way to calculate this setting automatically based on disk resources (log.retention.bytes is per partition setting and we do not know how many partitions we are going to have).

**Comment by joestein** [comment]
Yes, Kafka does not yet support a broker log retention value (https://issues.apache.org/jira/browse/KAFKA-1489). The log.retention.bytes is only for per partition yes. We don't know this value in the scheduler when we are first launching a broker because we don't know how many partitions there are.  Also this value is somewhat not useful because we don't know which partitions have more traffic. There could be 100 partitions but 1 that has 99% of the data compared to the others (a big Topic lets say) so even computing total partition count won't work for this upper value. Broker level log retention has been discussed in the Kafka community but not yet on a road map yet (we can look into doing that in the future, sure).

I don't think there is a good way to-do this right now without a human going in and setting --options log.retention.bytes=XYZ on start or after. We should update the README so folks know how to-do this, I can do this later on.

**Comment by joestein** [comment]
merged in #53

**Comment by amithrh** [comment]
I am using kafka .10 .
What does log.retention.bytes means ?
