### ISSUE TITLE
scheduler silently fails

### ISSUE THREAD

**Issue by vidhyaarvind** [mesos/kafka#82]
I have 2 kafka schedulers one for inbound and one for aggregate cluster. The first scheduler stays up . The second one silently fails every 7 mins without warning or error in the logs. I could create brokers. Could this be because of having the same zookeeper for both kafka clusters?

**Comment by serejja** [comment]
Hi vidhyaarvind, I've just successfully ran 2 schedulers:
1. Same configurations except --storage flag and --api flag to avoid "Address already in use" (explicitly pointing here that this configuration is using shared ZK and znode) worked fine and I was able to start brokers with different ids with both schedulers (ids should not intersect though because brokers will just fail on start).
2. Same as above but using different znodes worked even better - now both schedulers could have intersecting IDs and worked just fine.
3. If I started one scheduler with --storage file:kafka-mesos.json (default) and then tried to start the second scheduler with same storage file configured, the first scheduler died with following logs:

```
I0721 12:23:45.882612 16126 sched.cpp:815] Got error 'Framework failed over'
I0721 12:23:45.882642 16126 sched.cpp:1623] Asked to abort the driver
2015-07-21 12:23:45,882 [Thread-20] INFO  ly.stealth.mesos.kafka.Scheduler$  - [error] Framework failed over
```

but this looks reasonable to me as the second scheduler tries to register with the same framework id and Mesos notices that.

So no unexpected fails so far. 
Can you please post the scheduler parameters/property file entries that you use to start schedulers?
It would be great if I could try to reproduce with your exact steps.

Thanks

**Comment by joestein** [comment]
You should be using --storage file with zookeeper for everything
